.eslintrc, App/Components/Common/Icon/Constants.js, App/Components/Common/Icon/Icon.js, App/Components/TabBar/TabBarIcon.js, App/Components/TabBar/TabBarLabel.js, App/Components/TabBar/index.js, App/Navigation/MainTabNavigator.js, App/Screens/Calendar/Calendar.js, App/Screens/Calendar/index.js, App/Screens/ClassRooms/ClassRooms.js, App/Screens/ClassRooms/index.js, App/Screens/Profile/Profile.js, App/Screens/Profile/index.js
Implementacion del BottomTabBar, Navegacion del BottomTabBar a los distintos Screens, Creacion de Screens Del BottomTabBar. Se agrego tamaño 'TINY' al componente de Icons
=> BottomTabBar

App/Components/Common/DropDown/DropDown.js, App/Components/Common/DropDown/index.js, App/Components/FormikInput/DropDown.js, App/Components/FormikInput/index.js, package.json
Chequea a ver.. Lo hice casi igual que el text input, me dices si hay props que tengo que quitar..
<FormikInput
**type = "dropdown"**
label="Universidad"
**options={[{label: 'INTEC', value: '1'}, {label: 'UNIBE', value: '2'}]}**
name="university"
containerStyle={styles.input}
returnKeyType="done"
/>
=> Implement DropDown Component

App/Components/SubjectCalendar/SubjectCalendar.js, App/Components/SubjectCalendar/index.js
Ej: 
<SubjectCalendar
subjectName="Proyecto Final I pero imaginate que el nombre de la materia es más grande"
subjectSchedule="16:00 - 20:00"
onPress={() => {
alert('subject Pressed!');
}}
/>
=> SubjectCalendar component

App/Components/Common/Section/Section.js, App/Components/Common/Section/index.js, yarn.lock
- [x ] Probado en iOS Simulator/Device
- [ x] No existe ningun console log o warnings
Ej:
<Section title="Hello" >
<Text.SemiBold text="Qlk wawawa" />
</Section>
=> Section Component: done

.eslintrc, App/Components/Common/DropDown/DropDown.js, App/Components/Common/TextInput/TextInput.js, App/Components/LoadingState/LoadingState.js, App/Components/Login/LoginForm.js, App/Components/ModalForm/ModalForm.js, App/Components/Register/Register.js, App/Core/Api/Api.js, App/Core/Api/index.js, App/Core/LoggerMessages/Messages.js, App/Screens/Register/Register.js, package.json, yarn.lock
=> setup api and register backend

App/Components/Common/InLineComponent/InLineComponent.js, App/Components/SubjectCalendar/SubjectCalendar.js
=> Fix SubjectCalendarComponent use Children from inLineComponent

App/Components/Classes/Classes.js, App/Components/Classes/index.js, App/Screens/ClassRooms/ClassRooms.js
=> Implement classes screen

App/Components/SwipeableEventCalendar/SwipeableEventCalendar.js, App/Components/SwipeableEventCalendar/index.js, package.json, yarn.lock
Ej:
`
<SwipeableEventCalendar
subjectName="Proyecto Final I"
eventTitle="Entrega de Prototipos"
eventStartTime="22:00"
initialsText="FL"
author="Francine Lucca"
badgeUri="https://cdn0.iconfinder.com/data/icons/usa-politics/67/45-512.png"
onPress={() => {
alert('Event Pressed');
}}
onLeftSwipe={() => {
alert('Left Swipe');
}}
onRightSwipe={() => {
alert('Right Swipe');
}}
isPrivate
/>`
=> SwipeableEventCalendar Component: Done

App/Components/Home/Home.js
=> Fix console warn

App/Components/Login/LoginForm.js, App/Navigation/AuthNavigator.js, App/Screens/Login/Login.js, App/Screens/RecoverPassword/RecoverPassword.js, App/Screens/RecoverPassword/index.js
Implementar componente Link en LoginForm, Screen RecoverPassword (Vacio), Navegador de RecoverPassword
=> Implementar componente Link en LoginForm

.eslintrc, App/Screens/Home/Home.js
=> Add empty state in home

App/Components/SubjectPostRecent/SubjectPostRecent.js, App/Components/SubjectPostRecent/index.js
=> Implement subject post recent

App/Components/ClassInfoCard/ClassInfoCard.js, App/Components/Classes/Classes.js, App/Components/Common/Link/Link.js, App/Components/Common/Text/Text.js, App/Components/Home/Home.js, App/Components/Login/LoginForm.js, App/Core/Api/Api.js, App/Core/LoggerMessages/Messages.js, App/Models/MyClasses.js, App/Models/index.js, App/Navigation/AuthNavigator.js, App/Redux/Common/MyClasses/ActionTypes.js, App/Redux/Common/MyClasses/Actions.js, App/Redux/Common/MyClasses/Reducers.js, App/Redux/Common/MyClasses/Selectors.js, App/Redux/Common/MyClasses/index.js, App/Redux/RootReducer.js, App/Screens/ClassRooms/ClassRooms.js, App/Screens/Home/Home.js, App/Services/Logger/Logger.js, App/Utils/index.js, App/index.js, package.json, yarn.lock
=> Implement my classes and home fetching with backend

App/Components/Common/UpDownVoteSimple/UpDownVoteSimple.js, App/Components/Common/UpDownVoteSimple/index.js
=> Finished up and down vote simple

App/Navigation/MainTabNavigator.js
=> tabBarOnPress para abrir modal

App/Components/Common/BiButton/BiButton.js, App/Components/Common/Icon/Icon.js
=> BiButton add callback when unPressed and Icon make button optional

App/Components/Common/PopUp/PopUp.js, App/Components/Common/PopUp/index.js
=> Component: PopUp : developed

App/Components/Register/Register.js, App/Utils/index.js
=> Fix Password Regex, classNames

App/Components/ParticipantCard/ParticipantCard.js, App/Components/ParticipantCard/index.js
=> Component: ParticipantInfoCard

App/Components/DescriptiveInfoCard/DescriptiveInfoCard.js, App/Components/SubjectsByTeacher/SubjectsByTeacher.js, App/Components/SubjectsByTeacher/index.js, App/Models/TeacherResources.js, App/Models/index.js, App/Screens/SubjectsByTeacher/SubjectsByTeacher.js, App/Screens/SubjectsByTeacher/index.js
=> screen list teachers by subject done frontEnd

App/Components/Common/Avatar/Avatar.js, App/Components/ParticipantCard/ParticipantCard.js
=> align center avatar text and add margins so it doesn't go out of screen

App/Components/Common/DropDown/DropDown.js, App/Components/Common/Toggle/Constants.js, App/Components/Common/Toggle/Toggle.js, App/Components/Common/Toggle/index.js, App/Components/FormikInput/Toggle.js, App/Components/FormikInput/index.js
=> Formik Input on Toggle and Fix Formik on dropDown

App/Components/PostComments/PostComments.js
- [ x] Probado en iOS Simulator/Device
- [ x] No existe ningun console log o warnings
=> Implement clear text input on post comments

App/Components/PostComment/PostComment.js, App/Components/PostComments/PostComments.js, App/Screens/PostComments/PostComments.js
=> Arreglos varios de fontSizes

App/Components/Common/EnforcedToast/EnforcedToast.js, App/Components/Common/EnforcedToast/index.js, App/Components/Common/Toast/Toast.js, App/Components/Common/Toast/index.js
=> toast components

App/Components/Profile/Profile.js, App/Components/Profile/index.js, App/Screens/Profile/Profile.js
=> Finished profile screen.

App/Core/Assets/Fonts/index.js, App/Navigation/AppToken.js, App/index.js
=> Implementacion de Refresh Token

App/Components/EventForm/EventForm.js, App/Screens/EventForm/EventForm.js, App/Screens/PostInfo/PostInfo.js
=> Fix form when is editing the post

App/Screens/EventForm/EventForm.js
=> Fix error de fecha

App/Components/EventForm/EventForm.js, App/Components/FileInput/FileInput.js, App/Screens/EventForm/EventForm.js
=> Implement file input in attachments

App/Core/Api/Api.js, App/Redux/Common/MyClasses/Selectors.js, App/Redux/Common/UserManager/Selectors.js, App/Screens/Profile/Profile.js
=> BackEnd - MiPerfil

App/Components/Common/Toast/Toast.js, App/HOCs/WithLogger/WithLogger.js
Ejemplo de codigo:
`const { toastRef } = this.props;`
`const currentToast = Lodash.get(toastRef, ['current'], null)`
`if(current){`
`return current.setToastVisible(PARAMETRO_MENSAJE_TOAST, PARAMETRO_TIEMPO_DE_DURACION_DEL_TOAST)`
=> Set function to appear toast in any screen

App/Components/Common/ImagePicker/ImagePicker.js
=> Fix issue with imagepicker

App/Components/EventForm/EventForm.js, App/Screens/EventForm/EventForm.js
=> Fix issues with event form and validations after submit

App/Screens/PostComments/PostComments.js
=> Indicador cuando no hay comentarios en Post

App/Components/SettingsItemImagePicker/SettingsItemImagePicker.js
=> Fix image picker settings profile

App/Components/ClassHub/ClassHub.js, App/Components/SubjectPostRecent/SubjectPostRecent.js, App/Models/Posts.js
=> Add created since to a post

App/Screens/ClassParticipants/ClassParticipants.js
=> Agregar avatarURL a classParticipants

App/Screens/PostInfo/PostInfo.js
=> PostInfo hotfix

App/Screens/EventForm/EventForm.js
=> Fix issue with has date when the event form is editing

App/Components/EventForm/EventForm.js, App/Components/ModalForm/ModalForm.js, App/Core/Theme/Constants.js
=> Fix android issue with scroll

App/Components/Profile/Profile.js, App/Screens/Profile/Profile.js
=> Fix de mis clases en MyProfile Según New Change

App/Components/Profile/Profile.js, App/Screens/Profile/Profile.js
=> MyProfile add scrollView

App/Components/PostComments/PostComments.js
=> postComments : dont allow empty Comments

App/Components/PasswordRecoveryCode/PasswordRecoveryCode.js, App/Core/Api/Api.js, App/Screens/ChangePassword/ChangePassword.js, App/Screens/PasswordRecoveryCode/PasswordRecoveryCode.js, App/Screens/RecoverPassword/RecoverPassword.js
=> Recover Password Process

App/Components/Calendar/Calendar.js, App/Components/Classes/Classes.js, App/Components/Home/Home.js, App/Components/ViewProfile/ViewProfile.js, App/Core/Api/RegisterForNotifications.js, App/Models/Events.js, App/Screens/ClassRooms/ClassRooms.js, App/Screens/ViewProfile/ViewProfile.js
=> Calendar events and view profile fixes

App/Components/PostInfo/PostInfo.js, App/HOCs/WithLogger/WithLogger.js, App/Screens/EventForm/EventForm.js, App/Screens/PostComments/PostComments.js, App/Screens/PostInfo/PostInfo.js, App/Utils/index.js
=> Implementacion gamification

App/Redux/Common/UserManager/Selectors.js, App/Screens/Profile/Profile.js
=> BugFix My Profile, se agrego batchURL y Rank

App/Components/Calendar/Calendar.js, App/Components/ClassHub/ClassHub.js, App/Components/EventCalendar/EventCalendar.js, App/Components/EventForm/EventForm.js, App/Components/FileInput/FilePill.js, App/Components/Register/Register.js, App/Models/Events.js, App/Screens/EventForm/EventForm.js, App/Screens/ViewProfile/ViewProfile.js
=> Resolve issues in the app

App/Components/ChangePassword/ChangePassword.js, App/Components/ClassInfoCard/ClassInfoCard.js, App/Components/PostInfo/PostInfo.js, App/Components/Settings/Settings.js, App/Components/SyncComponent/SyncForm.js, App/Models/Participants.js, App/Models/PostCommentList.js, App/Screens/ChangePassword/ChangePassword.js, App/Screens/PasswordRecoveryCode/PasswordRecoveryCode.js, App/Screens/PostInfo/PostInfo.js, App/Screens/Settings/Settings.js, App/Screens/SyncAccount/SyncAccount.js
=> BugFixes Varios

App/Navigation/AuthNavigator.js, App/Screens/SyncAccount/SyncAccount.js
=> Swipe Navigation on Sync Screen

App/Navigation/MainTabNavigator.js, App/Screens/Home/Home.js
=> Navigation Fix

App/Components/SubTask/SubTask.js, App/Screens/PostInfo/PostInfo.js
=> SubTask + sign to the right

App/Components/EventForm/EventForm.js, App/Components/Login/LoginForm.js, App/Components/Register/Register.js
=> Teclado Hacer Click en Next para desplazarse hacia próximo Campo

App/Components/Home/Home.js, App/HOCs/WithLogger/WithLogger.js, App/Screens/Home/Home.js, App/index.js, package.json, yarn.lock
=> In app notification

App/Components/Calendar/Calendar.js, App/Components/Home/Home.js
=> Restyle info calendar events

App/Components/PostInfo/PostInfo.js, App/Screens/PostInfo/PostInfo.js
=> Quitar Ver Comentarios cuando Post es Privado en PostInfo

.yml
=> Add expo action

App/Components/SyncComponent/SyncForm.js
=> Make SyncForm more user-friendly

.github/workflows/main.yml
=> Git actions

.github/workflows/main.yml
=> test actions

App/Screens/Home/Home.js
=> Hotfix locale

.github/workflows/main.yml
=> hotfix actions

App/Components/Calendar/Calendar.js, App/Components/Home/Home.js
=> Fix Leyenda en Home y Calendario

App/Components/Common/TimePicker/TimePicker.js, App/Screens/PostInfo/PostInfo.js
=> Fix Bug TimePicker select hours adds 4

App/Components/Common/DropDown/DropDown.js, App/Components/PostInfo/PostInfo.js
=> DropDown: make more intuitive with down arrow on input:

App/Components/PostInfo/PostInfo.js
=> Dont Show Description Section if Post Doesn't Have it

App/Components/Home/Home.js, App/Navigation/MainTabNavigator.js, App/Screens/SyncAccount/SyncAccount.js
=> Fix Stack Problem y navigation a ChangePassword

App/Screens/ChangePassword/ChangePassword.js
=> fix changePassword navigation

App/Components/Calendar/Calendar.js, App/Components/Common/InfoCard/InfoCard.js, App/Components/Common/Link/Link.js, App/Components/EventCalendar/EventCalendar.js, App/Components/ParticipantCard/ParticipantCard.js, App/Components/PostComment/PostComment.js, App/Components/PostComments/PostComments.js, App/Components/PostInfo/PostInfo.js, App/Components/PostResourceRecent/PostResourceRecent.js, App/Components/SubjectPostRecent/SubjectPostRecent.js, App/Components/ViewProfile/ViewProfile.js, App/Screens/EventForm/EventForm.js, App/Screens/PostComments/PostComments.js
=> Fix UserName when name too long in multiple componentes/screens

App/HOCs/WithLogger/WithLogger.js, App/Screens/PostInfo/PostInfo.js
=> Implement on press in app notification

App/Components/Settings/Settings.js
=> Reorder settings items

App/Screens/PostInfo/PostInfo.js
=> postInfo: get class Name data from request

App/Components/Profile/Profile.js
=> change edit icon on my profile to settings icon

App/Components/Common/Avatar/Avatar.js, App/Components/EventCalendar/EventCalendar.js, App/Components/ParticipantCard/ParticipantCard.js, App/Components/PostComment/PostComment.js, App/Components/PostInfo/PostInfo.js
=> Cambio de font en Avatar

App/Screens/Settings/Settings.js
=> Android go to Notifications fix

App/Components/Common/DropDown/DropDown.js, App/Components/SyncComponent/SyncForm.js
=> Fix DropDown en Sync Screen

App/Components/Common/Avatar/Avatar.js, App/Components/EventCalendar/EventCalendar.js, App/Components/ParticipantCard/ParticipantCard.js, App/Components/PostComment/PostComment.js, App/Components/PostInfo/PostInfo.js
=> Avatar picture diamond issue fix

App/Navigation/MainTabNavigator.js
=> BugFix navigator en calendar

.eslintrc, App/Screens/Profile/Profile.js
=> fix request loop on MyProfile

App/Navigation/MainTabNavigator.js
=> Nav profile configuration fix

App/Components/ClassHub/ClassHub.js, App/Screens/ClassHub/ClassHub.js, App/Screens/Home/Home.js, App/Screens/PostComments/PostComments.js, App/Screens/SyncAccount/SyncAccount.js
=> Fix issue with sync required

App/Screens/PostInfo/PostInfo.js
=> Toast gamification upvote, downvote. Cambiado de 10 a 5.
